spring:
  application:
    name: dubbo-router-provider-v1.0.0
dubbo:
  application:
    id: dubbo-router-provider-v1.0.0
    name: dubbo-router-provider-v1.0.0
  protocol:
    name: dubbo
    port: 28883
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    check: false
server:
  port: 8001